from countryinfo import CountryInfo
count=input("Enter the name of your country : ")
country=CountryInfo(count)
print("The Capital : "+ country.capital())
print("The currency : ",country.currencies())
print("Language :", country.languages())
print("Borders : ", country.borders())
print("Other Names : ", country.alt_spellings())
print("Provinces are ", country.provinces())
print("Region : ", country.region())
print("Sub-Region : ", country.subregion())
print("Time Zone is ", country.timezones())
print("tld is ", country.tld())
print("Population : ", country.population())